# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13e4f3b8d5d32ee079bf45eb4e3ac8b22f7469d047852c5614ed75b8ab5642dd61e64a8c935b8d61ee9e252a525197e48fa3ac6f8c785b9fd57735fd949cc0e7

test:
  secret_key_base: 0eed5d0ef4369b6401408cea0fda3660554e9e0f4ff952b3d73e4111a0d32f62ab09dfc5e6332471842eff78112b6565defaa1fe68262d4f377badf719b799fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
